version: '2'
services:
    birdtheatre-app:
        image: birdtheatre
        external_links:
            - birdtheatre-mysql:mysql
            - birdtheatre-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/birdtheatre?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 3000:3000
    birdtheatre-mysql:
        extends:
            file: mysql.yml
            service: birdtheatre-mysql
    birdtheatre-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: birdtheatre-elasticsearch
